{{- $fullName := include "fullname" . -}}
{{- $host := .Values.ingress.host -}}
{{- $domain := .Values.ingress.domain -}}
{{- $port := .Values.deployment.port -}}
{{- $stage := .Values.data.environment.STAGE -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.{{ $host }}{{ $domain }}') {
        return 308 https://{{ $host }}{{ $domain }}$request_uri;
      }
spec:
  rules:
    {{ if eq $stage "production" }}
    - host: {{ $host }}{{ $domain }}
    {{ else }}
    - host: {{ $host }}-{{ $stage }}{{ $domain }}
    {{ end }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-service
              servicePort: {{ $port }}
    {{ if eq $stage "production" }}
    - host: {{ printf "www.%s%s" $host $domain }}
    {{ else }}
    - host: {{ printf "www.%s-%s%s" $host $stage $domain }}
    {{ end }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-service
              servicePort: {{ $port }}
              