{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-backend-{{ .Values.data.environment.STAGE }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{ if eq .Values.data.environment.STAGE "production" }}
  - host: demo.api.rex.vision
  {{ else }}
  - host: demo-development.api.rex.vision
  {{end}}
    http:
      paths:
        - backend:
            serviceName: {{ $fullName }}
            servicePort: {{ .Values.service.port }}
{{- end }}
