{{- if .Values.ingress.enabled -}}
# {{- $fullName := include "demo-backend.fullname" . -}}
# {{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    # helm.sh/chart: {{ include "demo-backend.chart" . }}
    helm.sh/chart: {{ .Release.chart }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{ if eq .Values.data.environment.STAGE "production" }}
  - host: demo.api.rex.vision
  {{ else }}
  - host: demo-development.api.rex.vision
  {{end}}
    http:
      paths:
        - backend:
            serviceName: demo-backend-{{ .Values.data.environment.STAGE }}
            servicePort: 3000 
{{- end }}
