apiVersion: v1
kind: Service
metadata:
  # name: {{ include "demo-backend.fullname" . }}
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    # helm.sh/chart: {{ include "demo-backend.chart" . }}
    helm.sh/chart: {{ include "{{ .Release.Name }}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
