# Default values for metric-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: localhost:5000/demo-backend
  tag: development-0.0.1
  pullPolicy: Always
  
  ingress:
    enabled: false
  
  service:
  type: NodePort
  port: 8080

# data:
#   environment: