# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

# image:
  # pullPolicy: IfNotPresent

data:
  IAM_ROLE: arn:aws:iam::900031763146:role/demo-backend-production
  environment:
    STAGE: "production"

# resources: {}
